stages:
  training:
    cmd: python src/training.py --config=params.yaml
    deps:
      - data/raw/train
      - data/raw/test
      - src/training.py
    params:
      - training.features
      - training.lr
      - training.visualize
      - training.epoches
      - mlflow_config.server_uri
      - mlflow_config.experiment_name
      - mlflow_config.run_name
      - mlflow_config.registered_model_name
    outs:
      - training_completion.txt

  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
      - src/log_production_model.py
      - training_completion.txt
    params:
      - mlflow_config.server_uri
      - mlflow_config.experiment_name
    outs:
      - saved_models/model.pth
