data:
  training_dir: data/raw/train/
  testing_dir: data/raw/test/

training:
  features: 8
  lr: 0.001
  visualize: False # run 'visdom' in terminal if set true
  epoches: 4
  batch_size: 32

mlflow_config:
  server_uri: sqlite:///mlflow.db
  experiment_name: Image Denoising
  run_name: 2st
  registered_model_name: AutoEncoder
